# Generated by Django 5.1.4 on 2025-01-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_alter_genre_id_alter_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='types',
            field=models.ManyToManyField(blank=True, null=True, related_name='books', to='admin_panel.type'),
        ),
    ]
