# Generated by Django 5.1.4 on 2025-01-18 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_alter_book_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='admin_panel.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='co_authors',
            field=models.ManyToManyField(blank=True, null=True, related_name='co_authored_books', to='admin_panel.author'),
        ),
    ]
