# Generated by Django 5.1.4 on 2025-01-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_alter_book_author_alter_book_co_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
