# Generated by Django 5.1.4 on 2025-01-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='co_authors',
            field=models.ManyToManyField(blank=True, related_name='co_authored_books', to='admin_panel.author'),
        ),
    ]
