# Generated by Django 5.1.4 on 2025-01-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_alter_book_co_authors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='types',
        ),
        migrations.AddField(
            model_name='book',
            name='type',
            field=models.ManyToManyField(blank=True, related_name='books', to='admin_panel.type'),
        ),
    ]
