# Generated by Django 5.1.4 on 2024-12-26 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customusermodel_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customusermodel',
            table='custom_user_model',
        ),
    ]
